version: "3.1"

services:
  db:
    image: postgres:13.7
    privileged: True
    restart: always
    ports:
      - 54325:5432
    environment:
      POSTGRES_USER: optikrus
      POSTGRES_PASSWORD: password123456
      POSTGRES_DB: catalog
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - .:/var/lib/postgresql/data
