version: "3.1"

services:
  db:
    image: postgres:13.7
    privileged: True
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: optikrus
      POSTGRES_PASSWORD: password123456
      POSTGRES_DB: catalog
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - .:/var/lib/postgresql/data

  backend:
    build:
      context: ../catalog
    privileged: True
    restart: always
    expose:
      - 8000
    command: bash -c "
      python manage.py migrate &&
      gunicorn catalog.wsgi -b 0.0.0.0:8000
      "
    environment:
      DJANGO_SETTINGS_MODULE: catalog.settings
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - 8002:8002
    depends_on:
      - backend
