# Generated by Django 4.0.4 on 2022-05-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='наименование товара')),
                ('date_delivery', models.DateTimeField(verbose_name='дата поступления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена за штуку')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('provider_name', models.CharField(max_length=256, unique=True, verbose_name='наименование товара')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
