# Generated by Django 4.0.4 on 2022-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_date_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider_name',
            field=models.CharField(max_length=256, unique=True, verbose_name='имя поставщика'),
        ),
    ]
