# Generated by Django 4.0.4 on 2022-06-07 13:27

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
