# Generated by Django 4.0.4 on 2022-06-07 13:41

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
